//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodWebAPI.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FoodDBEntities : DbContext
    {
        public FoodDBEntities()
            : base("name=FoodDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<City> City { get; set; }
        public virtual DbSet<Drink> Drink { get; set; }
        public virtual DbSet<Food> Food { get; set; }
        public virtual DbSet<Ingredient> Ingredient { get; set; }
        public virtual DbSet<Ingredient_To_Food> Ingredient_To_Food { get; set; }
        public virtual DbSet<Order> Order { get; set; }
        public virtual DbSet<Order_To_Drink> Order_To_Drink { get; set; }
        public virtual DbSet<Order_To_Food> Order_To_Food { get; set; }
        public virtual DbSet<Restaurant> Restaurant { get; set; }
    }
}
