//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodWebAPI.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_To_Drink
    {
        public int Id { get; set; }
        public int Id_Order { get; set; }
        public int Id_Drink { get; set; }
    
        public virtual Drink Drink { get; set; }
        public virtual Order Order { get; set; }
    }
}
