//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodAPI.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_To_Food
    {
        public int Id { get; set; }
        public string CustomerMessage { get; set; }
        public int Id_Order { get; set; }
        public int Id_Food { get; set; }
    
        public virtual Food Food { get; set; }
        public virtual Order Order { get; set; }
    }
}
